# /// script
# requires-python = ">=3.12"
# dependencies = ["numpy==2.2.6", "opencv-python-headless==4.12.0.88"]
# ///
"""Generate the committed reader benchmark report from the measured results.

    uv run tools/source_factory/readers/report.py

The report is generated, never hand-written, so a number in it cannot drift
away from the run that produced it. Source text is not reproduced: the report
carries measurements and provenance only.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from tools.source_factory.layout.corpus import load_document  # noqa: E402

TARGET = Path("docs/source-v2/BENCHMARK_READERS.md")


def cell(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def main() -> int:
    document = load_document(None)
    folder = document.folder / "readers" / "results"
    reports = [
        json.loads(path.read_text(encoding="utf-8")) for path in sorted(folder.glob("*.json"))
    ]
    if not reports:
        raise SystemExit(f"no results in {folder}")

    lines: list[str] = [
        "# Source V2 — Reader Benchmark",
        "",
        "Generated by `uv run tools/source_factory/readers/report.py` from the measured",
        "results on disk. Do not edit by hand.",
        "",
        "Specification: `prompts/source-v2/00_MASTER_SOURCE_V2_REBUILD.md`.",
        "Locked decisions: `docs/source-v2/DECISIONS.md` (D2 — readers are chosen by",
        "measurement, never by a published benchmark).",
        "",
        "## Corpus",
        "",
        f"- document: `{document.document_id}`, {document.dpi:.0f} dpi",
        "- crops: region crops cut deterministically from the fixed layout benchmark",
        "  pages by `tools/source_factory/readers/crops.py`; every reader sees the",
        "  identical pixels, so a difference is a difference in reading.",
        "",
        "## Environment",
        "",
    ]
    for report in reports:
        env = report.get("environment", {})
        lines.append(
            f"- `{report['reader']}`: torch {env.get('torch')}, transformers "
            f"{env.get('transformers')}, {env.get('device', 'no CUDA device')}"
        )
    lines += [
        "",
        "## Measured results",
        "",
        "| reader | crops | ran | failed | degenerate | mean s/crop | peak VRAM | mean CER | critical-token exact | mean foreign script |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for report in reports:
        summary = report["summary"]
        lines.append(
            "| `{reader}` | {crops} | {ran} | {failed} | {degenerate} | {secs} | {vram} | {cer} | {crit} | {foreign} |".format(
                reader=summary["reader"],
                crops=summary["crops"],
                ran=summary["ran"],
                failed=summary["failed"],
                degenerate=summary.get("degenerate", 0),
                secs=cell(summary["mean_seconds"]),
                vram=f"{summary['peak_vram_mib']} MiB" if summary.get("peak_vram_mib") else "—",
                cer=cell(summary["mean_cer"]),
                crit=summary["critical_token_exact"],
                foreign=cell(summary["mean_foreign_script"]),
            )
        )

    lines += ["", "## Critical tokens", "", "Where an unambiguous printed token was asserted:", ""]
    lines += ["| crop | expected | " + " | ".join(f"`{r['reader']}`" for r in reports) + " |"]
    lines += ["|---|---|" + "---|" * len(reports)]
    expectations: dict[str, list[str]] = {}
    for report in reports:
        for row in report.get("crops", []):
            if row.get("expected_tokens"):
                expectations[row["crop_id"]] = row["expected_tokens"]
    for crop_id, expected in sorted(expectations.items()):
        cells = []
        for report in reports:
            row = next((r for r in report["crops"] if r["crop_id"] == crop_id), None)
            if row is None:
                cells.append("—")
                continue
            found = set(row.get("found_tokens", []))
            cells.append(
                "all" if found == set(expected) else f"{len(found)}/{len(expected)}"
            )
        lines.append(f"| `{crop_id}` | {' '.join('`' + t + '`' for t in expected)} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## Per-crop timing and degeneration",
        "",
        "| crop | type | " + " | ".join(f"`{r['reader']}` s / chars / rep" for r in reports) + " |",
        "|---|---|" + "---|" * len(reports),
    ]
    crop_ids = sorted({row["crop_id"] for report in reports for row in report["crops"]})
    for crop_id in crop_ids:
        region_type = "—"
        cells = []
        for report in reports:
            row = next((r for r in report["crops"] if r["crop_id"] == crop_id), None)
            if row is None:
                cells.append("—")
                continue
            region_type = row["region_type"]
            flag = ""
            if row.get("repetition", 0) >= 0.5 or row.get("structural_repetition", 0) >= 0.6:
                flag = " **DEGENERATE**"
            cells.append(
                f"{row['seconds']:.1f} / {row['chars']} / {row.get('structural_repetition', 0):.2f}{flag}"
            )
        lines.append(f"| `{crop_id}` | {region_type} | " + " | ".join(cells) + " |")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"report": str(TARGET), "readers": [r["reader"] for r in reports]}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
