"""Provider-independent grounded question-generation contracts."""

from exam_guru_api.blueprints.domain import BlueprintSlot, BlueprintVersion, QuestionType
from exam_guru_api.generation.domain import (
    MAX_CONTEXT_CHARACTERS,
    MAX_CONTEXT_ITEM_CHARACTERS,
    MAX_CONTEXT_ITEMS,
    MAX_GENERATION_ATTEMPTS,
    MAX_OUTPUT_TOKENS,
    QUESTION_SCHEMA_VERSION,
    CandidateDisposition,
    ContextProvenance,
    ContextTrust,
    GeneratedQuestion,
    GenerationAccounting,
    GenerationContractError,
    GenerationIdentity,
    GenerationParameters,
    GenerationRequest,
    GenerationResult,
    GenerationVersions,
    MarkingCriterion,
    MarkingScheme,
    ProvenanceContext,
    QuestionAnswer,
    QuestionOption,
    RetrievedContextItem,
)
from exam_guru_api.generation.fakes import (
    DeterministicFakeGenerationProvider,
    DeterministicGenerationProvider,
)
from exam_guru_api.generation.ports import (
    GenerationProvider,
    ProviderError,
    ProviderFailure,
    ProviderFailureCode,
)
from exam_guru_api.generation.prompt_registry import (
    BoundPrompt,
    PromptAlreadyRegisteredError,
    PromptBindingError,
    PromptNotFoundError,
    PromptRegistry,
    PromptRegistryError,
    PromptTemplate,
)

__all__ = [
    "MAX_CONTEXT_CHARACTERS",
    "MAX_CONTEXT_ITEMS",
    "MAX_CONTEXT_ITEM_CHARACTERS",
    "MAX_GENERATION_ATTEMPTS",
    "MAX_OUTPUT_TOKENS",
    "QUESTION_SCHEMA_VERSION",
    "BlueprintSlot",
    "BlueprintVersion",
    "BoundPrompt",
    "CandidateDisposition",
    "ContextProvenance",
    "ContextTrust",
    "DeterministicFakeGenerationProvider",
    "DeterministicGenerationProvider",
    "GeneratedQuestion",
    "GenerationAccounting",
    "GenerationContractError",
    "GenerationIdentity",
    "GenerationParameters",
    "GenerationProvider",
    "GenerationRequest",
    "GenerationResult",
    "GenerationVersions",
    "MarkingCriterion",
    "MarkingScheme",
    "PromptAlreadyRegisteredError",
    "PromptBindingError",
    "PromptNotFoundError",
    "PromptRegistry",
    "PromptRegistryError",
    "PromptTemplate",
    "ProvenanceContext",
    "ProviderError",
    "ProviderFailure",
    "ProviderFailureCode",
    "QuestionAnswer",
    "QuestionOption",
    "QuestionType",
    "RetrievedContextItem",
]
