/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Audit Events */
        get: operations["list_admin_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List curriculum knowledge chunks */
        get: operations["list_knowledge_chunks"];
        put?: never;
        /** Import a draft educational knowledge chunk */
        post: operations["import_knowledge_chunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a curriculum knowledge chunk */
        get: operations["get_knowledge_chunk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/chunks/{chunk_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct a knowledge chunk classification */
        patch: operations["classify_knowledge_chunk"];
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/chunks/{chunk_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance a knowledge chunk review state */
        post: operations["transition_knowledge_chunk_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List curriculum historical questions */
        get: operations["list_historical_questions"];
        put?: never;
        /** Import a draft historical question */
        post: operations["import_historical_question"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a curriculum historical question */
        get: operations["get_historical_question"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/questions/{question_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct a historical question classification */
        patch: operations["classify_historical_question"];
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/knowledge/questions/{question_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance a historical question review state */
        post: operations["transition_historical_question_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/taxonomy/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List curriculum taxonomy nodes */
        get: operations["list_taxonomy_nodes"];
        put?: never;
        /** Create a curriculum taxonomy node */
        post: operations["create_taxonomy_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/taxonomy/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Taxonomy Node Route */
        patch: operations["update_taxonomy_node"];
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/taxonomy/nodes/{node_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Taxonomy Node Route */
        post: operations["deactivate_taxonomy_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curricula/{curriculum_version_id}/taxonomy/nodes/{node_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Taxonomy Node Route */
        post: operations["review_taxonomy_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curriculum-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Curriculum Versions */
        get: operations["list_curriculum_versions"];
        put?: never;
        /** Create Curriculum Version */
        post: operations["create_curriculum_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/curriculum-versions/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Curriculum Version */
        patch: operations["update_curriculum_version"];
        trace?: never;
    };
    "/api/v1/admin/curriculum-versions/{resource_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Curriculum Version */
        post: operations["deactivate_curriculum_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exam Configurations */
        get: operations["list_exam_configurations"];
        put?: never;
        /** Create Exam Configuration */
        post: operations["create_exam_configuration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-configurations/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Exam Configuration */
        patch: operations["update_exam_configuration"];
        trace?: never;
    };
    "/api/v1/admin/exam-configurations/{resource_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Exam Configuration */
        post: operations["deactivate_exam_configuration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media"];
        put?: never;
        /** Create Medium */
        post: operations["create_medium"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Medium */
        patch: operations["update_medium"];
        trace?: never;
    };
    "/api/v1/admin/media/{resource_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Medium */
        post: operations["deactivate_medium"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Documents */
        get: operations["list_source_documents"];
        put?: never;
        /** Upload Source Document */
        post: operations["upload_source_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Source Document Extraction */
        post: operations["trigger_source_document_extraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Document Pages */
        get: operations["list_source_document_pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/pages/{page_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Source Document Page */
        patch: operations["correct_source_document_page"];
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/pages/{page_number}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Page Blocks */
        get: operations["list_source_page_blocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/pages/{page_number}/blocks/{reading_order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Source Document Block */
        patch: operations["correct_source_document_block"];
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin Source Document Review */
        post: operations["begin_source_document_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/source-documents/{document_id}/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trust Source Document */
        post: operations["trust_source_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API liveness */
        get: operations["get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API dependencies */
        get: operations["get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminAuditEventResponse */
        AdminAuditEventResponse: {
            /** Action */
            action: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
        };
        /** Body_upload_source_document */
        Body_upload_source_document: {
            /** Curriculum Version Id */
            curriculum_version_id?: string | null;
            document_type: components["schemas"]["SourceDocumentType"];
            /** File */
            file: string;
            /** Paper Code */
            paper_code?: string | null;
            /** Year */
            year?: number | null;
        };
        /**
         * ChunkType
         * @enum {string}
         */
        ChunkType: "competency_section" | "learning_outcome" | "explanation" | "example" | "practice_question" | "key_term";
        /** CurriculumVersionCreate */
        CurriculumVersionCreate: {
            /** Code */
            code: string;
            /**
             * Exam Configuration Id
             * Format: uuid
             */
            exam_configuration_id: string;
            /**
             * Medium Id
             * Format: uuid
             */
            medium_id: string;
            /** Title */
            title: string;
        };
        /** CurriculumVersionResponse */
        CurriculumVersionResponse: {
            /** Active */
            active: boolean;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Exam Configuration Id
             * Format: uuid
             */
            exam_configuration_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medium Id
             * Format: uuid
             */
            medium_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CurriculumVersionUpdate */
        CurriculumVersionUpdate: {
            /** Title */
            title: string;
        };
        /** DependencyChecks */
        DependencyChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Valkey
             * @enum {string}
             */
            valkey: "ok" | "unavailable";
        };
        /** EmbeddingConfigurationMetadataResponse */
        EmbeddingConfigurationMetadataResponse: {
            /** Config Fingerprint */
            config_fingerprint: string;
            /** Dimension */
            dimension: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Version */
            version: string;
        };
        /**
         * EmbeddingStatus
         * @enum {string}
         */
        EmbeddingStatus: "not_embedded" | "embedded";
        /** ExamConfigurationCreate */
        ExamConfigurationCreate: {
            /** Code */
            code: string;
            /**
             * Grade
             * @constant
             */
            grade: 5;
            /** Name */
            name: string;
        };
        /** ExamConfigurationResponse */
        ExamConfigurationResponse: {
            /** Active */
            active: boolean;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Grade */
            grade: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExamConfigurationUpdate */
        ExamConfigurationUpdate: {
            /** Name */
            name: string;
        };
        /** ExtractedBlockResponse */
        ExtractedBlockResponse: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Character Count */
            character_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Extractor */
            extractor: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Number */
            page_number: number;
            /** Raw Text */
            raw_text: string;
            /** Reading Order */
            reading_order: number;
            /** Reviewed Text */
            reviewed_text: string | null;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /**
             * Source Page Id
             * Format: uuid
             */
            source_page_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ExtractionJobResponse */
        ExtractionJobResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Message Id */
            message_id: string;
            status: components["schemas"]["ExtractionStatus"];
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "uploaded" | "extraction_pending" | "extracted" | "in_review" | "trusted" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoricalQuestionImportRequest */
        HistoricalQuestionImportRequest: {
            /** Marks */
            marks: number;
            /** Page Number */
            page_number: number;
            /** Paper Code */
            paper_code: string;
            /** Question Number */
            question_number: string;
            question_type: components["schemas"]["QuestionType"];
            /**
             * Source Block Id
             * Format: uuid
             */
            source_block_id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Text */
            text: string;
            /** Year */
            year: number;
        };
        /** HistoricalQuestionResponse */
        HistoricalQuestionResponse: {
            classification: components["schemas"]["KnowledgeClassificationResponse"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Curriculum Version Id
             * Format: uuid
             */
            curriculum_version_id: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Embedding Configurations */
            embedding_configurations: components["schemas"]["EmbeddingConfigurationMetadataResponse"][];
            embedding_status: components["schemas"]["EmbeddingStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Marks */
            marks: number;
            /** Paper Code */
            paper_code: string;
            provenance: components["schemas"]["KnowledgeProvenanceResponse"];
            /** Question Number */
            question_number: string;
            question_type: components["schemas"]["QuestionType"];
            review_state: components["schemas"]["ReviewState"];
            /** Text */
            text: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Year */
            year: number;
        };
        /** KnowledgeChunkImportRequest */
        KnowledgeChunkImportRequest: {
            chunk_type: components["schemas"]["ChunkType"];
            /** Educational Boundary */
            educational_boundary: string;
            /** Page Number */
            page_number: number;
            /** Sequence */
            sequence: number;
            /**
             * Source Block Id
             * Format: uuid
             */
            source_block_id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Text */
            text: string;
        };
        /** KnowledgeChunkResponse */
        KnowledgeChunkResponse: {
            chunk_type: components["schemas"]["ChunkType"];
            classification: components["schemas"]["KnowledgeClassificationResponse"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Curriculum Version Id
             * Format: uuid
             */
            curriculum_version_id: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Educational Boundary */
            educational_boundary: string;
            /** Embedding Configurations */
            embedding_configurations: components["schemas"]["EmbeddingConfigurationMetadataResponse"][];
            embedding_status: components["schemas"]["EmbeddingStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            provenance: components["schemas"]["KnowledgeProvenanceResponse"];
            review_state: components["schemas"]["ReviewState"];
            /** Sequence */
            sequence: number;
            /** Text */
            text: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** KnowledgeClassificationRequest */
        KnowledgeClassificationRequest: {
            /** Competency Id */
            competency_id?: string | null;
            /** Expected Version */
            expected_version: number;
            /** Learning Concept Id */
            learning_concept_id?: string | null;
            /** Skill Id */
            skill_id?: string | null;
            /** Sub Skill Id */
            sub_skill_id?: string | null;
        };
        /** KnowledgeClassificationResponse */
        KnowledgeClassificationResponse: {
            /** Competency Id */
            competency_id: string | null;
            /** Learning Concept Id */
            learning_concept_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Sub Skill Id */
            sub_skill_id: string | null;
        };
        /** KnowledgeProvenanceResponse */
        KnowledgeProvenanceResponse: {
            /** Page Number */
            page_number: number;
            /** Source Block Id */
            source_block_id: string | null;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
        };
        /** KnowledgeReviewTransitionRequest */
        KnowledgeReviewTransitionRequest: {
            /** Expected Version */
            expected_version: number;
            target: components["schemas"]["ReviewState"];
        };
        /** MediumCreate */
        MediumCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** MediumResponse */
        MediumResponse: {
            /** Active */
            active: boolean;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MediumUpdate */
        MediumUpdate: {
            /** Name */
            name: string;
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "multiple_choice" | "short_answer" | "structured";
        /** ReadinessResponse */
        ReadinessResponse: {
            checks: components["schemas"]["DependencyChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /**
         * ReviewState
         * @enum {string}
         */
        ReviewState: "draft" | "in_review" | "reviewed" | "rejected";
        /** ReviewedTextUpdate */
        ReviewedTextUpdate: {
            /** Expected Version */
            expected_version: number;
            /** Reviewed Text */
            reviewed_text: string;
        };
        /** SourceDocumentResponse */
        SourceDocumentResponse: {
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Curriculum Version Id */
            curriculum_version_id: string | null;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            document_type: components["schemas"]["SourceDocumentType"];
            /** Extracted Block Count */
            extracted_block_count: number | null;
            /** Extracted Character Count */
            extracted_character_count: number | null;
            /** Extracted Page Count */
            extracted_page_count: number | null;
            /** Extraction Attempt Count */
            extraction_attempt_count: number;
            /** Extraction Completed At */
            extraction_completed_at: string | null;
            /** Extraction Failure Code */
            extraction_failure_code: string | null;
            /** Extraction Started At */
            extraction_started_at: string | null;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extractor */
            extractor: string | null;
            /** Extractor Version */
            extractor_version: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Native Text Page Ratio */
            native_text_page_ratio: number | null;
            /** Needs Ocr */
            needs_ocr: boolean | null;
            /** Original Filename */
            original_filename: string;
            /** Paper Code */
            paper_code: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Year */
            year: number | null;
        };
        /**
         * SourceDocumentType
         * @enum {string}
         */
        SourceDocumentType: "syllabus" | "teacher_guide" | "past_paper" | "marking_scheme" | "evaluation_report" | "other_approved";
        /** SourcePageResponse */
        SourcePageResponse: {
            /** Block Count */
            block_count: number;
            /** Character Count */
            character_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Extractor */
            extractor: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Number */
            page_number: number;
            /** Raw Text */
            raw_text: string;
            /** Reviewed Text */
            reviewed_text: string | null;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * TaxonomyLevel
         * @enum {string}
         */
        TaxonomyLevel: "competency" | "skill" | "sub_skill" | "learning_concept";
        /** TaxonomyNodeCreate */
        TaxonomyNodeCreate: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Code */
            code: string;
            level: components["schemas"]["TaxonomyLevel"];
            /** Parent Id */
            parent_id?: string | null;
            /** Title */
            title: string;
        };
        /** TaxonomyNodeResponse */
        TaxonomyNodeResponse: {
            /** Active */
            active: boolean;
            /** Code */
            code: string;
            /**
             * Curriculum Version Id
             * Format: uuid
             */
            curriculum_version_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            level: components["schemas"]["TaxonomyLevel"];
            /** Parent Id */
            parent_id: string | null;
            review_state: components["schemas"]["TaxonomyReviewState"];
            /** Title */
            title: string;
        };
        /** TaxonomyNodeUpdate */
        TaxonomyNodeUpdate: {
            /** Code */
            code: string;
            /** Title */
            title: string;
        };
        /**
         * TaxonomyReviewState
         * @enum {string}
         */
        TaxonomyReviewState: "draft" | "reviewed" | "deprecated";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_admin_audit_events: {
        parameters: {
            query?: {
                limit?: number;
                resource_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_chunks: {
        parameters: {
            query?: {
                review_state?: components["schemas"]["ReviewState"] | null;
                source_document_id?: string | null;
                competency_id?: string | null;
                chunk_type?: components["schemas"]["ChunkType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_knowledge_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeChunkImportRequest"];
            };
        };
        responses: {
            /** @description Existing source chunk returned idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft knowledge chunk imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkResponse"];
                };
            };
            /** @description Conflicting source import */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Knowledge invariant failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_knowledge_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_knowledge_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_knowledge_chunk_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeReviewTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_historical_questions: {
        parameters: {
            query?: {
                review_state?: components["schemas"]["ReviewState"] | null;
                source_document_id?: string | null;
                competency_id?: string | null;
                question_type?: components["schemas"]["QuestionType"] | null;
                year?: number | null;
                paper_code?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalQuestionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_historical_question: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalQuestionImportRequest"];
            };
        };
        responses: {
            /** @description Existing source question returned idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft historical question imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalQuestionResponse"];
                };
            };
            /** @description Conflicting source import */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Knowledge invariant failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_historical_question: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_historical_question: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_historical_question_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeReviewTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_taxonomy_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_taxonomy_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyNodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeResponse"];
                };
            };
            /** @description Curriculum version not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Taxonomy conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid taxonomy hierarchy */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_taxonomy_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyNodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_taxonomy_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_taxonomy_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curriculum_version_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_curriculum_versions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumVersionResponse"][];
                };
            };
        };
    };
    create_curriculum_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurriculumVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_curriculum_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurriculumVersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_curriculum_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_configurations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamConfigurationResponse"][];
                };
            };
        };
    };
    create_exam_configuration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamConfigurationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamConfigurationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exam_configuration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamConfigurationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamConfigurationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_exam_configuration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamConfigurationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediumResponse"][];
                };
            };
        };
    };
    create_medium: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediumCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_medium: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediumUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_medium: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_documents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"][];
                };
            };
        };
    };
    upload_source_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_document"];
            };
        };
        responses: {
            /** @description Existing checksum returned idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source document created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Upload validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_source_document_extraction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_document_pages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_source_document_page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewedTextUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_page_blocks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedBlockResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_source_document_block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_number: number;
                reading_order: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewedTextUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedBlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_source_document_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trust_source_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
